[categories.lazyvim-minimal]
aliases = ["lzv-min"]
description = "Minimal LazyVim dependencies and editor setup"
debian_packages = ["git", "curl", "clang", "fd-find", "lazygit"]
termux_packages = ["neovim", "git", "curl", "clang", "fd", "lazygit"]

[categories.lazyvim-minimal.custom.debian]
name = "neovim"
type = "github_release_tarball"
url = "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
extract_dir = "/opt/nvim"
bin_symlink = "~/.local/bin/nvim"
